### PR TITLE
add more details on RDS exam power up

### PR DESCRIPTION
**Pull request by lordz-md**

### CODE REVIEW

**Comment by awsbhadhya** [comment]
AWS

**Comment by lordz-md** [comment]
> AWS

!?

**Comment by awsbhadhya** [comment]
> > AWS
> 
> !?

sorry by mistake..

**Review by alozano-77 — APPROVED** [review]
Thanks for the corrections and patiently for the merge.

**Comment by alozano-77** [comment]
Merged into master by making Lambda@edge it's own (1/2) section. Will account for numbering in the future.

**Pull request merged**
